backend/everpro/Url-Shortener/url_shortener/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('router.urls') )
]

backend/everpro/chat/urls.py
from django.contrib.auth.views import logout
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('chat/', views.chat_view, name='chats'),
    path('chat/<int:sender>/<int:receiver>/', views.message_view, name='chat'),
    path('api/messages/<int:sender>/<int:receiver>/', views.message_list, name='message-detail'),
    path('api/messages/', views.message_list, name='message-list'),
    path('logout/', logout, {'next_page': 'index'}, name='logout'),
    path('register/', views.register_view, name='register'),
]

backend/everpro/django-affiliate-marketing-master/dashboard/urls.py
from django.urls import path
from .views import DashboardView, OffersView, AffiliatesView, PaymentsView, SupportView, \
    UserDetailView, StatusView, SmartLinksView, EarningsCreateView, EarningsUpdateView, EarningsDeleteView, \
    PaymentsCreateView, PaymentsUpdateView, PaymentsDeleteView, \
    OffersCreateView, OffersUpdateView, OffersDeleteView, \
    SupportManagerView, SupportManagerCreateView, SupportManagerUpdateView, SupportManagerDeleteView, \
    BalanceUpdateView, UserCreateView, UserUpdateView, UserDeleteView


app_name = 'dashboard'

urlpatterns = [
    path('', DashboardView.as_view(), name='dashboard'),
    path('affiliates/', AffiliatesView.as_view(), name='affiliates'),
    path('user/<int:pk>/', UserDetailView.as_view(), name='user-detail'),
    path('user/create/', UserCreateView.as_view(), name='create-user'),
    path('user/update/<int:pk>', UserUpdateView.as_view(), name='update-user'),
    path('user/delete/<int:pk>', UserDeleteView.as_view(), name='delete-user'),

    path('offers/', OffersView.as_view(), name='offers'),
    path('offers/create/', OffersCreateView.as_view(), name='create-offers'),
    path('offers/update/<int:pk>', OffersUpdateView.as_view(), name='update-offers'),
    path('offers/delete/<int:pk>', OffersDeleteView.as_view(), name='delete-offers'),

    path('earning/create/<slug:slug>', EarningsCreateView.as_view(), name='create-earning'),
    path('earning/update/<int:pk>-<slug:slug>', EarningsUpdateView.as_view(), name='update-earning'),
    path('earning/delete/<int:pk>-<slug:slug>', EarningsDeleteView.as_view(), name='delete-earning'),

    path('payment/create/<slug:slug>', PaymentsCreateView.as_view(), name='create-payment'),
    path('payment/update/<int:pk>-<slug:slug>', PaymentsUpdateView.as_view(), name='update-payment'),
    path('payment/delete/<int:pk>-<slug:slug>', PaymentsDeleteView.as_view(), name='delete-payment'),

    path('balance/update/<int:pk>-<slug:slug>', BalanceUpdateView.as_view(), name='update-balance'),

    path('status/', StatusView.as_view(), name='status'),
    path('smart-links/', SmartLinksView.as_view(), name='smart-links'),
    path('payments/', PaymentsView.as_view(), name='payments'),

    path('support/', SupportView.as_view(), name='support'),
    path('support-manager/', SupportManagerView.as_view(), name='support-manager'),
    path('support-manager/create/', SupportManagerCreateView.as_view(), name='create-support-manager'),
    path('support-manager/update/<int:pk>', SupportManagerUpdateView.as_view(), name='update-support-manager'),
    path('support-manager/delete/<int:pk>', SupportManagerDeleteView.as_view(), name='delete-support-manager'),
]

backend/everpro/django-affiliate-marketing-master/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('', TemplateView.as_view(template_name='profiles/home.html'), name='home'),
]

backend/everpro/django-affiliate-marketing-master/profiles/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView
from .views import SignupView, delete_user
from .forms import LoginForm

app_name = 'profiles'

urlpatterns = [
    path('', TemplateView.as_view(template_name='profiles/home.html'), name='home'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='profiles/login.html', authentication_form=LoginForm),
         name='auth_login'),
    path('logout/', auth_views.logout_then_login, name='auth_logout'),
    path('user/<int:pk>/delete', delete_user, name='user-delete')
]

backend/everpro/everpro/urls.py
from django.contrib import admin
from django.urls import include, path

from django.views.generic import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", TemplateView.as_view(template_name="index.html")),
    path("", include("inventory_scrapping.urls")),
    path("", include("competition_tracking.urls")),
    path("search/", include("search.urls")),
]

backend/everpro/paypal/donation/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('payment/', include('payments.urls'))
]

backend/everpro/django-affiliate-marketing-master/common/models.py
from django.db import models

# Create your models here.

backend/everpro/django-affiliate-marketing-master/dashboard/models.py
from django.db import models
from django.conf import settings
from django.utils.translation import ugettext as _
from decimal import Decimal


class Earnings(models.Model):
    customer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='earnings')

    earning_date = models.DateTimeField(_('Date'))
    hits = models.IntegerField(_('Hits'), default=0)
    leads = models.IntegerField(_('Leads'), default=0)
    money = models.DecimalField(_('Money'), max_digits=6, decimal_places=2)

    class Meta:
        ordering = ('-earning_date',)


class Payments(models.Model):
    TYPE_CHOICES = [
        ('regular', 'Regular'),
        ('commercial', 'Commercial'),
        ('progress', 'Progress'),
    ]
    STATUS_CHOICES = [
        ('paid', 'Paid'),
        ('unpaid', 'Unpaid'),
    ]

    customer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='payments')

    payment_date = models.DateTimeField(_('Date'))
    invoice_id = models.IntegerField(_('Invoice ID'))
    type = models.CharField(max_length=32, choices=TYPE_CHOICES, null=True, default=TYPE_CHOICES[0][0])
    amount = models.DecimalField(_('Amount'), max_digits=6, decimal_places=2)
    status = models.CharField(max_length=16, choices=STATUS_CHOICES, null=True, default=STATUS_CHOICES[0][0])

    class Meta:
        ordering = ('-payment_date',)


class SmartLinks(models.Model):
    customer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='smartlinks')
    smart_link = models.CharField(_('Smart Link'), max_length=255)

    class Meta:
        ordering = ['-id']


class SupportManager(models.Model):
    AVATAR_CHOICES = [
        ('m-01', 'Male-01'),
        ('f-01', 'Female-01'),
        ('m-02', 'Male-02'),
        ('f-02', 'Female-02'),
        ('m-03', 'Male-03'),
        ('f-03', 'Female-03'),
        ('m-04', 'Male-04'),
        ('f-04', 'Female-04'),
        ('m-05', 'Male-05'),
        ('f-05', 'Female-05'),
        ('m-06', 'Male-06'),
        ('f-06', 'Female-06'),
        ('m-07', 'Male-07'),
        ('f-07', 'Female-07'),
        ('m-08', 'Male-08'),
        ('f-08', 'Female-08'),
        ('m-09', 'Male-09'),
        ('f-09', 'Female-09'),
        ('m-10', 'Male-10'),
        ('f-10', 'Female-10')
    ]
    name = models.CharField(_('full name'), max_length=255)
    avatar = models.CharField(_('avatar'), max_length=32, choices=AVATAR_CHOICES, null=True,
                              default=AVATAR_CHOICES[0][0])
    email = models.EmailField(_('email address'), max_length=255)
    phone_number = models.CharField(_('phone number'), max_length=60)
    skype = models.CharField(_('skype'), max_length=255, null=True, blank=True)
    website = models.CharField(_('website'), max_length=255, null=True, blank=True)

    class Meta:
        ordering = ['-id']


class Balance(models.Model):
    customer = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='balance')
    balance = models.DecimalField(_('Balance'), max_digits=6, default=Decimal('0.00'), decimal_places=2)

    class Meta:
        ordering = ['-id']

backend/everpro/django-affiliate-marketing-master/common/views.py
from django.shortcuts import render

# Create your views here.

backend/everpro/django-affiliate-marketing-master/dashboard/views.py
from django.views.generic.list import ListView
from django.shortcuts import redirect
from django.urls import reverse_lazy
from bootstrap_modal_forms.generic import BSModalCreateView, BSModalUpdateView, BSModalDeleteView
from common.mixins import LoginRequiredMixin
from .models import SmartLinks, Earnings, Payments, SupportManager, Balance
from .forms import SmartLinksForm, EarningsForm, PaymentsForm, SupportManagerForm, BalanceForm, UserForm
from profiles.models import User


class DashboardView(LoginRequiredMixin, ListView):
    success_url = '/dashboard/'
    template_name = 'dashboard/overview.html'
    model = User
    context_object_name = 'users'

    def get(self, request, *args, **kwargs):
        if not self.request.user.is_superuser:
            return redirect("dashboard:status")
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        return User.objects.exclude(email=self.request.user.email)


class UserDetailView(LoginRequiredMixin, ListView):
    template_name = 'dashboard/user-detail.html'
    model = Earnings
    context_object_name = 'earnings'

    def get_context_data(self, **kwargs):
        context = super(UserDetailView, self).get_context_data(**kwargs)

        customer = User.objects.get(pk=self.kwargs.get('pk'))
        context['customer'] = customer
        context['payments'] = Payments.objects.filter(customer=customer)
        context['smart_links'] = SmartLinks.objects.filter(customer=customer)
        return context

    def get_queryset(self):
        customer = User.objects.get(pk=self.kwargs.get('pk'))
        return Earnings.objects.filter(customer=customer)


class OffersView(LoginRequiredMixin, ListView):
    success_url = '/dashboard/offers/'
    template_name = 'dashboard/offers.html'
    model = SmartLinks
    context_object_name = 'smart_links'
    paginate_by = 10


class AffiliatesView(LoginRequiredMixin, ListView):
    success_url = '/dashboard/affiliates/'
    template_name = 'dashboard/affiliates.html'
    model = User
    context_object_name = 'users'


class StatusView(LoginRequiredMixin, ListView):
    success_url = '/dashboard/status/'
    template_name = 'dashboard/status.html'
    model = Earnings
    context_object_name = 'earnings'
    paginate_by = 30

    def get_queryset(self):
        return Earnings.objects.filter(customer=self.request.user)


class SmartLinksView(LoginRequiredMixin, ListView):
    success_url = '/dashboard/smart-links/'
    template_name = 'dashboard/smart-links.html'
    model = SmartLinks
    context_object_name = 'smart_links'
    paginate_by = 30

    def get_queryset(self):
        return SmartLinks.objects.filter(customer=self.request.user)


class PaymentsView(LoginRequiredMixin, ListView):
    success_url = '/dashboard/payments/'
    template_name = 'dashboard/payments.html'
    model = Payments
    context_object_name = 'payments'
    paginate_by = 30

    def get_queryset(self):
        return Payments.objects.filter(customer=self.request.user)


class SupportView(LoginRequiredMixin, ListView):
    success_url = '/dashboard/support/'
    template_name = 'dashboard/support.html'
    model = SupportManager
    context_object_name = 'supports'


class EarningsCreateView(BSModalCreateView):
    template_name = 'dashboard/include/create-modal.html'
    form_class = EarningsForm
    success_message = 'New earning has been created successfully'

    def get_success_url(self):
        if 'slug' in self.kwargs:
            slug = self.kwargs['slug']
        else:
            slug = 0
        return reverse_lazy('dashboard:user-detail', kwargs={'pk': slug})


class EarningsUpdateView(BSModalUpdateView):
    model = Earnings
    template_name = 'dashboard/include/update-modal.html'
    form_class = EarningsForm
    success_message = 'An earning has been updated successfully'

    def get_success_url(self):
        if 'slug' in self.kwargs:
            slug = self.kwargs['slug']
        else:
            slug = 0
        return reverse_lazy('dashboard:user-detail', kwargs={'pk': slug})


class EarningsDeleteView(BSModalDeleteView):
    model = Earnings
    template_name = 'dashboard/include/delete-modal.html'
    success_message = 'An earning has been deleted successfully'

    def get_success_url(self):
        if 'slug' in self.kwargs:
            slug = self.kwargs['slug']
        else:
            slug = 0
        return reverse_lazy('dashboard:user-detail', kwargs={'pk': slug})


class PaymentsCreateView(BSModalCreateView):
    template_name = 'dashboard/include/create-modal.html'
    form_class = PaymentsForm
    success_message = 'New payment has been created successfully'

    def get_success_url(self):
        if 'slug' in self.kwargs:
            slug = self.kwargs['slug']
        else:
            slug = 0
        return reverse_lazy('dashboard:user-detail', kwargs={'pk': slug})


class PaymentsUpdateView(BSModalUpdateView):
    model = Payments
    template_name = 'dashboard/include/update-modal.html'
    form_class = PaymentsForm
    success_message = 'A payment has been updated successfully'

    def get_success_url(self):
        if 'slug' in self.kwargs:
            slug = self.kwargs['slug']
        else:
            slug = 0
        return reverse_lazy('dashboard:user-detail', kwargs={'pk': slug})


class PaymentsDeleteView(BSModalDeleteView):
    model = Payments
    template_name = 'dashboard/include/delete-modal.html'
    success_message = 'A payment has been deleted successfully'

    def get_success_url(self):
        if 'slug' in self.kwargs:
            slug = self.kwargs['slug']
        else:
            slug = 0
        return reverse_lazy('dashboard:user-detail', kwargs={'pk': slug})


class UserCreateView(BSModalCreateView):
    template_name = 'dashboard/include/create-modal.html'
    form_class = UserForm
    success_message = 'New user has been created successfully'
    success_url = reverse_lazy('dashboard:affiliates')


class UserUpdateView(BSModalUpdateView):
    model = User
    template_name = 'dashboard/include/update-modal.html'
    form_class = UserForm
    success_message = 'An user has been updated successfully'
    success_url = reverse_lazy('dashboard:affiliates')


class UserDeleteView(BSModalDeleteView):
    model = User
    template_name = 'dashboard/include/delete-modal.html'
    success_message = 'An user has been deleted successfully'
    success_url = reverse_lazy('dashboard:affiliates')


class OffersCreateView(BSModalCreateView):
    template_name = 'dashboard/include/create-modal.html'
    form_class = SmartLinksForm
    success_message = 'New smart link has been created successfully'
    success_url = reverse_lazy('dashboard:offers')


class OffersUpdateView(BSModalUpdateView):
    model = SmartLinks
    template_name = 'dashboard/include/update-modal.html'
    form_class = SmartLinksForm
    success_message = 'A smart link has been updated successfully'
    success_url = reverse_lazy('dashboard:offers')


class OffersDeleteView(BSModalDeleteView):
    model = SmartLinks
    template_name = 'dashboard/include/delete-modal.html'
    success_message = 'A smart link has been deleted successfully'
    success_url = reverse_lazy('dashboard:offers')


class SupportManagerView(LoginRequiredMixin, ListView):
    success_url = '/dashboard/support-manager/'
    template_name = 'dashboard/support-manager.html'
    model = SupportManager
    context_object_name = 'supports'


class SupportManagerCreateView(BSModalCreateView):
    template_name = 'dashboard/include/create-modal.html'
    form_class = SupportManagerForm
    success_message = 'New support manager has been created successfully'
    success_url = reverse_lazy('dashboard:support-manager')


class SupportManagerUpdateView(BSModalUpdateView):
    model = SupportManager
    template_name = 'dashboard/include/update-modal.html'
    form_class = SupportManagerForm
    success_message = 'A support manager has been updated successfully'
    success_url = reverse_lazy('dashboard:support-manager')


class SupportManagerDeleteView(BSModalDeleteView):
    model = SupportManager
    template_name = 'dashboard/include/delete-modal.html'
    success_message = 'A smart link has been deleted successfully'
    success_url = reverse_lazy('dashboard:support-manager')


class BalanceUpdateView(BSModalUpdateView):
    model = Balance
    template_name = 'dashboard/include/update-modal.html'
    form_class = BalanceForm
    success_message = 'Balance has been updated successfully'
    success_url = reverse_lazy('dashboard:support-manager')

    def get_success_url(self):
        if 'slug' in self.kwargs:
            slug = self.kwargs['slug']
        else:
            slug = 0
        return reverse_lazy('dashboard:user-detail', kwargs={'pk': slug})

backend/everpro/django-affiliate-marketing-master/templates/dashboard/include/_modal.html
<div class="modal fade" tabindex="-1" role="dialog" id="modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content"></div>
  </div>
</div>

backend/everpro/django-affiliate-marketing-master/templates/dashboard/include/base-modal.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">{{ title }}</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">

    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>

    {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" placeholder=field.label %}
        <div class="{% if field.errors %} invalid{% endif %}">
          {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
          {% endfor %}
        </div>
      </div>
    {% endfor %}
  </div>

  <div class="modal-footer">
    <button type="button" class="submit-btn btn btn-primary">{{ title }}</button>
  </div>

</form>

<script>
  $(function () {
    if($('#id_earning_date')) {
      $('#id_earning_date').datetimepicker({
        format: 'YYYY-MM-DD HH:mm:ss'
      });
    }
    if($('#id_payment_date')) {
      $('#id_payment_date').datetimepicker({
        format: 'YYYY-MM-DD HH:mm:ss'
      });
    }
  });
</script>

backend/everpro/django-affiliate-marketing-master/templates/dashboard/include/bs4_form.html
{% load widget_tweaks %}

{% for hidden_field in form.hidden_fields %}
  {{ hidden_field }}
{% endfor %}

{% if form.non_field_errors %}
  <div class="alert alert-danger" role="alert">
    {% for error in form.non_field_errors %}
      {{ error }}
    {% endfor %}
  </div>
{% endif %}

{% for field in form.visible_fields %}
  <div class="form-group">
    {{ field.label_tag }}

    {% if form.is_bound %}
      {% if field.errors %}
        {% render_field field class="form-control is-invalid" %}
        {% for error in field.errors %}
          <div class="invalid-feedback">
            {{ error }}
          </div>
        {% endfor %}
      {% else %}
        {% render_field field class="form-control is-valid" %}
      {% endif %}
    {% else %}
      {% render_field field class="form-control" %}
    {% endif %}

    {% if field.help_text %}
      <small class="form-text text-muted">{{ field.help_text }}</small>
    {% endif %}
  </div>
{% endfor %}

backend/everpro/django-affiliate-marketing-master/templates/dashboard/include/create-modal.html
{% include "dashboard/include/base-modal.html" with title='Create' %}

backend/everpro/django-affiliate-marketing-master/templates/dashboard/include/layout.html
{% load i18n static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
  <title>EverPro V2.0 | Dashboard</title>
  <meta name="description" content="EverPro V2.0">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no">

  <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/logo.png' %}" />

  <link href="{% static 'plugins/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css" />
  <link href="{% static 'plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}" rel="stylesheet" type="text/css" />
  <link href="{% static 'plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}" rel="stylesheet" type="text/css" />

  <link href="{% static 'plugins/adminlte/css/adminlte.min.css' %}" rel="stylesheet" type="text/css" />
  <link href="{% static 'plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}" rel="stylesheet" type="text/css" />

  {% block extrastyle %}{% endblock %}
  {% block extrahead %}{% endblock %}

</head>
{% load i18n %}

<body class="hold-transition sidebar-mini layout-fixed">
  <div class="wrapper">
    <nav class="main-header navbar navbar-expand navbar-light navbar-white">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i> </a>
        </li>
      </ul>

      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <span class="nav-link">Balance: <strong>${{ user.get_balance|default:'0'|floatformat:2 }}</strong></span>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link" data-toggle="dropdown" href="#">
            <i class="far fa-user"></i>
          </a>

          {% if user.is_authenticated %}
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
              <a href="#" class="dropdown-item">
                <!-- Message Start -->
                <div class="media">
                  <img src="{% static 'img/user-pic-default.png' %}" alt="User Avatar" class="img-size-50 mr-3 img-circle">
                  <div class="media-body">
                    <h3 class="dropdown-item-title">{{ user.get_full_name|default:"No Name" }}</h3>
                    <p class="text-sm">{{ user.email }}</p>
                  </div>
                </div>
                <!-- Message End -->
              </a>
              <div class="dropdown-divider"></div>
              <a href="{% url 'profiles:auth_logout' %}" class="dropdown-item dropdown-footer">Log Out</a>
            </div>
          {% endif %}

        </li>
      </ul>
    </nav>

    <aside class="main-sidebar sidebar-dark-primary elevation-4">
      <!-- Brand Logo -->
      <a href="#" class="brand-link">
        <img src="{% static 'img/logo.png' %}" alt="Logo" class="brand-image img-circle elevation-3"
             style="opacity: .8">
        <span class="brand-text font-weight-light">EverPro V2.0</span>
      </a>

      <!-- Sidebar -->
      {% block sidebar %}
      {% endblock %}
      <!-- /.sidebar -->
    </aside>

    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      {%  block content-header %}
      {% endblock %}
      <!-- /.content-header -->

      <!-- Main content -->
      <section class="content">
        <div class="container-fluid">
          {% block content %}
          {% endblock %}
        </div>
      </section>
    </div>

    <footer class="main-footer">
      <div class="float-right d-none d-sm-inline">
        <b>Version</b> 1.0.0
      </div>
      <strong>Copyright &copy; 2015-2019 <a href="/">EverPro V2.0</a>.</strong>
      All rights reserved.
    </footer>
    {% block extrafooter %}{% endblock %}
  </div>

  <script src="{% static 'plugins/jquery/jquery.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'plugins/jquery-ui/jquery-ui.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'plugins/moment/moment.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}" type="text/javascript"></script>

  <script src="{% static 'plugins/adminlte/js/adminlte.min.js' %}" type="text/javascript"></script>
  {% block sub_extra_script %}

{% endblock %}

</body>
</html>

backend/everpro/django-affiliate-marketing-master/templates/dashboard/include/sidebar.html
<div class="sidebar">
  <!-- Sidebar Menu -->
  <nav class="mt-2">
    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
      <!-- Add icons to the links using the .nav-icon class
           with font-awesome or any other icon font library -->
    {% if user.is_superuser %}
      <li class="nav-item">
        <a href="{% url 'dashboard:dashboard' %}" class="nav-link{% if active == 'Dashboard' %} active{% endif %}">
          <i class="nav-icon fas fa-tachometer-alt"></i>
          <p>Dashboard</p>
        </a>
      </li>

      <li class="nav-item">
        <a href="{% url 'dashboard:offers' %}" class="nav-link{% if active == 'Offers' %} active{% endif %}">
          <i class="nav-icon fas fa-flag"></i>
          <p>Offers</p>
        </a>
      </li>

      <li class="nav-item">
        <a href="{% url 'dashboard:affiliates' %}" class="nav-link{% if active == 'Affiliates' %} active{% endif %}">
          <i class="nav-icon fas fa-user"></i>
          <p>Affiliates</p>
        </a>
      </li>

      <li class="nav-item">
        <a href="{% url 'dashboard:support-manager' %}" class="nav-link{% if active == 'Support' %} active{% endif %}">
          <i class="nav-icon fas fa-envelope"></i>
          <p>Support</p>
        </a>
      </li>
    {% else %}
      <li class="nav-item">
        <a href="{% url 'dashboard:status' %}" class="nav-link{% if active == 'Status' %} active{% endif %}">
          <i class="nav-icon fas fa-tachometer-alt"></i>
          <p>Status</p>
        </a>
      </li>

      <li class="nav-item">
        <a href="{% url 'dashboard:smart-links' %}" class="nav-link{% if active == 'Smart Links' %} active{% endif %}">
          <i class="nav-icon fas fa-star"></i>
          <p>Smart Links</p>
        </a>
      </li>

      <li class="nav-item">
        <a href="{% url 'dashboard:payments' %}" class="nav-link{% if active == 'Payments' %} active{% endif %}">
          <i class="nav-icon fas fa-toolbox"></i>
          <p>Payments</p>
        </a>
      </li>

      <li class="nav-item">
        <a href="{% url 'dashboard:support' %}" class="nav-link{% if active == 'Support' %} active{% endif %}">
          <i class="nav-icon fas fa-envelope"></i>
          <p>Support</p>
        </a>
      </li>
    {% endif %}

    </ul>
  </nav>
  <!-- /.sidebar-menu -->
</div>

backend/everpro/django-affiliate-marketing-master/templates/dashboard/include/update-modal.html
{% include "dashboard/include/base-modal.html" with title='Update' %}