backend/everpro/chat/urls.py
from django.contrib.auth.views import logout
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('chat/', views.chat_view, name='chats'),
    path('chat/<int:sender>/<int:receiver>/', views.message_view, name='chat'),
    path('api/messages/<int:sender>/<int:receiver>/', views.message_list, name='message-detail'),
    path('api/messages/', views.message_list, name='message-list'),
    path('logout/', logout, {'next_page': 'index'}, name='logout'),
    path('register/', views.register_view, name='register'),
]

backend/everpro/django-affiliate-marketing-master/dashboard/urls.py
from django.urls import path
from .views import DashboardView, OffersView, AffiliatesView, PaymentsView, SupportView, \
    UserDetailView, StatusView, SmartLinksView, EarningsCreateView, EarningsUpdateView, EarningsDeleteView, \
    PaymentsCreateView, PaymentsUpdateView, PaymentsDeleteView, \
    OffersCreateView, OffersUpdateView, OffersDeleteView, \
    SupportManagerView, SupportManagerCreateView, SupportManagerUpdateView, SupportManagerDeleteView, \
    BalanceUpdateView, UserCreateView, UserUpdateView, UserDeleteView


app_name = 'dashboard'

urlpatterns = [
    path('', DashboardView.as_view(), name='dashboard'),
    path('affiliates/', AffiliatesView.as_view(), name='affiliates'),
    path('user/<int:pk>/', UserDetailView.as_view(), name='user-detail'),
    path('user/create/', UserCreateView.as_view(), name='create-user'),
    path('user/update/<int:pk>', UserUpdateView.as_view(), name='update-user'),
    path('user/delete/<int:pk>', UserDeleteView.as_view(), name='delete-user'),

    path('offers/', OffersView.as_view(), name='offers'),
    path('offers/create/', OffersCreateView.as_view(), name='create-offers'),
    path('offers/update/<int:pk>', OffersUpdateView.as_view(), name='update-offers'),
    path('offers/delete/<int:pk>', OffersDeleteView.as_view(), name='delete-offers'),

    path('earning/create/<slug:slug>', EarningsCreateView.as_view(), name='create-earning'),
    path('earning/update/<int:pk>-<slug:slug>', EarningsUpdateView.as_view(), name='update-earning'),
    path('earning/delete/<int:pk>-<slug:slug>', EarningsDeleteView.as_view(), name='delete-earning'),

    path('payment/create/<slug:slug>', PaymentsCreateView.as_view(), name='create-payment'),
    path('payment/update/<int:pk>-<slug:slug>', PaymentsUpdateView.as_view(), name='update-payment'),
    path('payment/delete/<int:pk>-<slug:slug>', PaymentsDeleteView.as_view(), name='delete-payment'),

    path('balance/update/<int:pk>-<slug:slug>', BalanceUpdateView.as_view(), name='update-balance'),

    path('status/', StatusView.as_view(), name='status'),
    path('smart-links/', SmartLinksView.as_view(), name='smart-links'),
    path('payments/', PaymentsView.as_view(), name='payments'),

    path('support/', SupportView.as_view(), name='support'),
    path('support-manager/', SupportManagerView.as_view(), name='support-manager'),
    path('support-manager/create/', SupportManagerCreateView.as_view(), name='create-support-manager'),
    path('support-manager/update/<int:pk>', SupportManagerUpdateView.as_view(), name='update-support-manager'),
    path('support-manager/delete/<int:pk>', SupportManagerDeleteView.as_view(), name='delete-support-manager'),
]

backend/everpro/everpro/urls.py
from django.contrib import admin
from django.urls import include, path

from django.views.generic import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", TemplateView.as_view(template_name="index.html")),
    path("", include("inventory_scrapping.urls")),
    path("", include("competition_tracking.urls")),
    path("search/", include("search.urls")),
]

backend/everpro/paypal/donation/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('payment/', include('payments.urls'))
]

backend/everpro/paypal/payments/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

backend/everpro/django-affiliate-marketing-master/common/models.py
from django.db import models

# Create your models here.

backend/everpro/django-affiliate-marketing-master/dashboard/forms.py
from django import forms
from django.forms import widgets
from django.utils.safestring import mark_safe
from decimal import Decimal
from bootstrap_modal_forms.forms import BSModalForm
from .models import SmartLinks, Earnings, Payments, SupportManager, Balance
from profiles.models import User

TYPE_CHOICES = [
    ('regular', 'Regular'),
    ('commercial', 'Commercial'),
    ('progress', 'Progress'),
]
STATUS_CHOICES = [
    ('paid', 'Paid'),
    ('unpaid', 'Unpaid'),
]


class SmartLinksForm(BSModalForm):
    customer = forms.ModelChoiceField(queryset=User.objects.all().order_by('email'), widget=forms.Select(),
                                      empty_label=None)

    smart_link = forms.CharField(
        max_length=255,
        widget=forms.TextInput(attrs={'class': 'form-control m-input m-input--square', 'placeholder': 'Smart Link'})
    )

    class Meta:
        model = SmartLinks
        fields = ('customer', 'smart_link')


class DateTimePickerWidget(widgets.TextInput):
    def render(self, name, value, attrs=None, renderer=None):
        return mark_safe(u'''<div class="input-group date" id="id_%s" data-target-input="nearest">%s<div class=
        "input-group-append" data-target="#id_%s" data-toggle="datetimepicker"><div class="input-group-text">
        <i class="far fa-calendar-alt"></i></div></div></div>''' %
                         (name, super(DateTimePickerWidget, self).render(name, value, attrs), name))


class EarningsForm(BSModalForm):
    customer = forms.ModelChoiceField(queryset=User.objects.all().order_by('email'), widget=forms.Select(),
                                      empty_label=None)

    earning_date = forms.DateTimeField(
        widget=DateTimePickerWidget(attrs={
            'class': 'form-control datetimepicker-input',
            'id': 'earning_date',
            'data-target': '#id_earning_date'
        })
    )

    hits = forms.IntegerField(widget=forms.NumberInput(attrs={
        'class': 'form-control',
        'min': '0'
    }))

    leads = forms.IntegerField(widget=forms.NumberInput(attrs={
        'class': 'form-control',
        'min': '0'
    }))

    money = forms.DecimalField(widget=forms.NumberInput(attrs={
        'class': 'form-control'
    }), min_value=Decimal('0.00'))

    class Meta:
        model = Earnings
        fields = ('customer', 'earning_date', 'hits', 'leads', 'money')


class PaymentsForm(BSModalForm):
    customer = forms.ModelChoiceField(queryset=User.objects.all().order_by('email'), widget=forms.Select(),
                                      empty_label=None)

    payment_date = forms.DateTimeField(
        widget=DateTimePickerWidget(attrs={
            'class': 'form-control',
            'id': 'payment_date',
            'data-target': '#id_payment_date'
        })
    )

    invoice_id = forms.IntegerField(widget=forms.NumberInput(attrs={
        'class': 'form-control',
        'min': '0'
    }))

    type = forms.ChoiceField(choices=TYPE_CHOICES, widget=forms.Select())

    amount = forms.DecimalField(widget=forms.NumberInput(attrs={
        'class': 'form-control'
    }), min_value=Decimal('0.00'))

    status = forms.ChoiceField(choices=STATUS_CHOICES, widget=forms.Select())

    class Meta:
        model = Payments
        fields = ('customer', 'payment_date', 'invoice_id', 'type', 'amount', 'status')


class SupportManagerForm(BSModalForm):
    class Meta:
        model = SupportManager
        fields = ('name', 'email', 'avatar', 'phone_number', 'skype', 'website')


class UserForm(BSModalForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'is_active', 'is_superuser')


class BalanceForm(BSModalForm):
    class Meta:
        model = Balance
        fields = ('balance',)

backend/everpro/django-affiliate-marketing-master/common/views.py
from django.shortcuts import render

# Create your views here.

backend/everpro/django-affiliate-marketing-master/dashboard/views.py
from django.views.generic.list import ListView
from django.shortcuts import redirect
from django.urls import reverse_lazy
from bootstrap_modal_forms.generic import BSModalCreateView, BSModalUpdateView, BSModalDeleteView
from common.mixins import LoginRequiredMixin
from .models import SmartLinks, Earnings, Payments, SupportManager, Balance
from .forms import SmartLinksForm, EarningsForm, PaymentsForm, SupportManagerForm, BalanceForm, UserForm
from profiles.models import User


class DashboardView(LoginRequiredMixin, ListView):
    success_url = '/dashboard/'
    template_name = 'dashboard/overview.html'
    model = User
    context_object_name = 'users'

    def get(self, request, *args, **kwargs):
        if not self.request.user.is_superuser:
            return redirect("dashboard:status")
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        return User.objects.exclude(email=self.request.user.email)


class UserDetailView(LoginRequiredMixin, ListView):
    template_name = 'dashboard/user-detail.html'
    model = Earnings
    context_object_name = 'earnings'

    def get_context_data(self, **kwargs):
        context = super(UserDetailView, self).get_context_data(**kwargs)

        customer = User.objects.get(pk=self.kwargs.get('pk'))
        context['customer'] = customer
        context['payments'] = Payments.objects.filter(customer=customer)
        context['smart_links'] = SmartLinks.objects.filter(customer=customer)
        return context

    def get_queryset(self):
        customer = User.objects.get(pk=self.kwargs.get('pk'))
        return Earnings.objects.filter(customer=customer)


class OffersView(LoginRequiredMixin, ListView):
    success_url = '/dashboard/offers/'
    template_name = 'dashboard/offers.html'
    model = SmartLinks
    context_object_name = 'smart_links'
    paginate_by = 10


class AffiliatesView(LoginRequiredMixin, ListView):
    success_url = '/dashboard/affiliates/'
    template_name = 'dashboard/affiliates.html'
    model = User
    context_object_name = 'users'


class StatusView(LoginRequiredMixin, ListView):
    success_url = '/dashboard/status/'
    template_name = 'dashboard/status.html'
    model = Earnings
    context_object_name = 'earnings'
    paginate_by = 30

    def get_queryset(self):
        return Earnings.objects.filter(customer=self.request.user)


class SmartLinksView(LoginRequiredMixin, ListView):
    success_url = '/dashboard/smart-links/'
    template_name = 'dashboard/smart-links.html'
    model = SmartLinks
    context_object_name = 'smart_links'
    paginate_by = 30

    def get_queryset(self):
        return SmartLinks.objects.filter(customer=self.request.user)


class PaymentsView(LoginRequiredMixin, ListView):
    success_url = '/dashboard/payments/'
    template_name = 'dashboard/payments.html'
    model = Payments
    context_object_name = 'payments'
    paginate_by = 30

    def get_queryset(self):
        return Payments.objects.filter(customer=self.request.user)


class SupportView(LoginRequiredMixin, ListView):
    success_url = '/dashboard/support/'
    template_name = 'dashboard/support.html'
    model = SupportManager
    context_object_name = 'supports'


class EarningsCreateView(BSModalCreateView):
    template_name = 'dashboard/include/create-modal.html'
    form_class = EarningsForm
    success_message = 'New earning has been created successfully'

    def get_success_url(self):
        if 'slug' in self.kwargs:
            slug = self.kwargs['slug']
        else:
            slug = 0
        return reverse_lazy('dashboard:user-detail', kwargs={'pk': slug})


class EarningsUpdateView(BSModalUpdateView):
    model = Earnings
    template_name = 'dashboard/include/update-modal.html'
    form_class = EarningsForm
    success_message = 'An earning has been updated successfully'

    def get_success_url(self):
        if 'slug' in self.kwargs:
            slug = self.kwargs['slug']
        else:
            slug = 0
        return reverse_lazy('dashboard:user-detail', kwargs={'pk': slug})


class EarningsDeleteView(BSModalDeleteView):
    model = Earnings
    template_name = 'dashboard/include/delete-modal.html'
    success_message = 'An earning has been deleted successfully'

    def get_success_url(self):
        if 'slug' in self.kwargs:
            slug = self.kwargs['slug']
        else:
            slug = 0
        return reverse_lazy('dashboard:user-detail', kwargs={'pk': slug})


class PaymentsCreateView(BSModalCreateView):
    template_name = 'dashboard/include/create-modal.html'
    form_class = PaymentsForm
    success_message = 'New payment has been created successfully'

    def get_success_url(self):
        if 'slug' in self.kwargs:
            slug = self.kwargs['slug']
        else:
            slug = 0
        return reverse_lazy('dashboard:user-detail', kwargs={'pk': slug})


class PaymentsUpdateView(BSModalUpdateView):
    model = Payments
    template_name = 'dashboard/include/update-modal.html'
    form_class = PaymentsForm
    success_message = 'A payment has been updated successfully'

    def get_success_url(self):
        if 'slug' in self.kwargs:
            slug = self.kwargs['slug']
        else:
            slug = 0
        return reverse_lazy('dashboard:user-detail', kwargs={'pk': slug})


class PaymentsDeleteView(BSModalDeleteView):
    model = Payments
    template_name = 'dashboard/include/delete-modal.html'
    success_message = 'A payment has been deleted successfully'

    def get_success_url(self):
        if 'slug' in self.kwargs:
            slug = self.kwargs['slug']
        else:
            slug = 0
        return reverse_lazy('dashboard:user-detail', kwargs={'pk': slug})


class UserCreateView(BSModalCreateView):
    template_name = 'dashboard/include/create-modal.html'
    form_class = UserForm
    success_message = 'New user has been created successfully'
    success_url = reverse_lazy('dashboard:affiliates')


class UserUpdateView(BSModalUpdateView):
    model = User
    template_name = 'dashboard/include/update-modal.html'
    form_class = UserForm
    success_message = 'An user has been updated successfully'
    success_url = reverse_lazy('dashboard:affiliates')


class UserDeleteView(BSModalDeleteView):
    model = User
    template_name = 'dashboard/include/delete-modal.html'
    success_message = 'An user has been deleted successfully'
    success_url = reverse_lazy('dashboard:affiliates')


class OffersCreateView(BSModalCreateView):
    template_name = 'dashboard/include/create-modal.html'
    form_class = SmartLinksForm
    success_message = 'New smart link has been created successfully'
    success_url = reverse_lazy('dashboard:offers')


class OffersUpdateView(BSModalUpdateView):
    model = SmartLinks
    template_name = 'dashboard/include/update-modal.html'
    form_class = SmartLinksForm
    success_message = 'A smart link has been updated successfully'
    success_url = reverse_lazy('dashboard:offers')


class OffersDeleteView(BSModalDeleteView):
    model = SmartLinks
    template_name = 'dashboard/include/delete-modal.html'
    success_message = 'A smart link has been deleted successfully'
    success_url = reverse_lazy('dashboard:offers')


class SupportManagerView(LoginRequiredMixin, ListView):
    success_url = '/dashboard/support-manager/'
    template_name = 'dashboard/support-manager.html'
    model = SupportManager
    context_object_name = 'supports'


class SupportManagerCreateView(BSModalCreateView):
    template_name = 'dashboard/include/create-modal.html'
    form_class = SupportManagerForm
    success_message = 'New support manager has been created successfully'
    success_url = reverse_lazy('dashboard:support-manager')


class SupportManagerUpdateView(BSModalUpdateView):
    model = SupportManager
    template_name = 'dashboard/include/update-modal.html'
    form_class = SupportManagerForm
    success_message = 'A support manager has been updated successfully'
    success_url = reverse_lazy('dashboard:support-manager')


class SupportManagerDeleteView(BSModalDeleteView):
    model = SupportManager
    template_name = 'dashboard/include/delete-modal.html'
    success_message = 'A smart link has been deleted successfully'
    success_url = reverse_lazy('dashboard:support-manager')


class BalanceUpdateView(BSModalUpdateView):
    model = Balance
    template_name = 'dashboard/include/update-modal.html'
    form_class = BalanceForm
    success_message = 'Balance has been updated successfully'
    success_url = reverse_lazy('dashboard:support-manager')

    def get_success_url(self):
        if 'slug' in self.kwargs:
            slug = self.kwargs['slug']
        else:
            slug = 0
        return reverse_lazy('dashboard:user-detail', kwargs={'pk': slug})

backend/everpro/django-affiliate-marketing-master/profiles/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy
from django.shortcuts import redirect
from django.contrib import messages
from .forms import SignUpForm
from .models import User


# Create your views here.
class SignupView(CreateView):
    template_name = 'profiles/signup.html'
    form_class = SignUpForm
    success_url = reverse_lazy('profiles:auth_login')


def delete_user(request, pk):
    user = User.objects.get(id=pk)
    user.delete()
    messages.success(request, 'An user has been deleted successfully.')
    return redirect("dashboard:affiliates")

backend/everpro/paypal/payments/views.py
from django.shortcuts import render

# Create your views here.


def index(request):
    return render(request, 'payments/index.html')

backend/everpro/django-affiliate-marketing-master/templates/dashboard/overview.html
{% extends "dashboard/include/layout.html" %}

{% load static %}

{% block sidebar %}
{% include "dashboard/include/sidebar.html" with active='Dashboard' %}
{% endblock %}

{% block content-header %}
  {% include "dashboard/include/content-header.html" with header='Dashboard' %}
{% endblock %}

{% block content %}
  {% if users %}
    <h5 class="mb-2">Registrations <span class="badge badge-info right">{{ users|length }}</span></h5>
    {% for user in users %}
      {% if forloop.first %}<div class="row">{% endif %}
      <div class="col-lg-4 col-md-6 col-sm-12">
        <div class="info-box">
          <a href="{% url 'dashboard:user-detail' user.id %}" class="info-box-icon bg-info"><i class="far fa-user"></i></a>

          <div class="info-box-content">
            <span class="info-box-text">{{ user.get_full_name|default:"No Name" }}</span>
            <span class="info-box-number">{{ user.email }}</span>
            <span>{{ user.date_joined|timesince }}</span>
          </div>
        </div>
      </div>
      {% if forloop.counter|divisibleby:3 %}</div><div class="row">{% endif %}
      {% if forloop.last %}</div>{% endif %}

    {% endfor %}
  {% endif %}
{% endblock content %}

backend/everpro/django-affiliate-marketing-master/templates/dashboard/user-detail.html
{% extends "dashboard/include/layout.html" %}

{% load static %}

{% block sidebar %}
{% include "dashboard/include/sidebar.html" with active='Dashboard' %}
{% endblock %}

{% block content-header %}
  {% include "dashboard/include/content-header.html" with header='Dashboard' %}
{% endblock %}

{% block content %}

  {% include "dashboard/include/_modal.html" %}

  {% if customer %}
    <div class="row">
      <div class="card card-widget widget-user" style="width: 100%;">
        <!-- Add the bg color to the header using any of the bg-* classes -->
        <div class="widget-user-header bg-info">
          <h3 class="widget-user-username">{{ customer.get_full_name|default:"No Name" }}</h3>
          <h5 class="widget-user-desc">{{ customer.email }}</h5>
        </div>
        <div class="widget-user-image">
          <img class="img-circle elevation-2" src="{% static 'img/user-pic-default.png' %}" alt="User Avatar">
        </div>
        <div class="card-footer">
          <div class="row">
            <div class="col-sm-4 border-right">
              <div class="description-block">
                <h5 class="description-header">{% if earnings %}{{ earnings|length }}{% else %}0{% endif %}</h5>
                <span class="description-text">Earnings</span>
              </div>
              <!-- /.description-block -->
            </div>
            <!-- /.col -->
            <div class="col-sm-4 border-right">
              <div class="description-block">
                <h5 class="description-header">{% if payments %}{{ payments|length }}{% else %}0{% endif %}</h5>
                <span class="description-text">Payments</span>
              </div>
              <!-- /.description-block -->
            </div>
            <!-- /.col -->
            <div class="col-sm-4">
              <div class="description-block">
                <h5 class="description-header">{% if smart_links %}{{ smart_links|length }}{% else %}0{% endif %}</h5>
                <span class="description-text">Smart Links</span>
              </div>
              <!-- /.description-block -->
            </div>
            <!-- /.col -->
          </div>
          <!-- /.row -->
        </div>
      </div>
    </div>

    <div class="row">
      <div class="card" style="width: 100%;">
        <div class="card-header">
          <h3 class="card-title">Balance: <strong class="text-info">$ {{ customer.get_balance|default:'0'|floatformat:2 }}</strong></h3>

          <div class="card-tools">
            <ul class="pagination pagination-sm float-right">
              <li class="page-item">
                <a class="update-balance page-link" href="#" data-id="{% url 'dashboard:update-balance' customer.balance.pk customer.pk %}">
                  <i class="fa fa-pen"></i> Edit
                </a>
              </li>
            </ul>
          </div>
        </div>
        <!-- /.card-header -->
      </div>
    </div>

    <div class="row">
      <div class="card" style="width: 100%;">
        <div class="card-header">
          <h3 class="card-title">Earnings</h3>

          <div class="card-tools">
            <ul class="pagination pagination-sm float-right">
              <li class="page-item">
                <a class="create-earnings page-link" href="#">
                  <i class="fa fa-plus"></i> New
                </a>
              </li>
            </ul>
          </div>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
          <div class="dataTables_wrapper dt-bootstrap4">
            <table id="earnings-table" class="table table-bordered table-hover">
              <thead>
              <tr>
                <th class="text-center" scope="col">#</th>
                <th class="text-center" scope="col">Date</th>
                <th class="text-center" scope="col">Hits</th>
                <th class="text-center" scope="col">Leads</th>
                <th class="text-center" scope="col">Money</th>
                <th class="text-center" scope="col">Action</th>
              </tr>
              </thead>
              <tbody>
              {% for earning in earnings %}
                <tr>
                  <td class="text-center" scope="row">{{ forloop.counter }}</td>
                  <td class="text-center">{{ earning.earning_date }}</td>
                  <td class="text-center">{{ earning.hits }}</td>
                  <td class="text-center">{{ earning.leads }}</td>
                  <td class="text-center">$ {{ earning.money }}</td>
                  <td class="text-center">
                    <button type="button" class="update-earnings btn btn-sm btn-primary" data-id="{% url 'dashboard:update-earning' earning.pk customer.pk %}">
                      <span class="fa fa-pen"></span>
                    </button>
                    <button type="button" class="delete-earnings btn btn-sm btn-danger" data-id="{% url 'dashboard:delete-earning' earning.pk customer.pk %}">
                      <span class="fa fa-trash"></span>
                    </button>
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
        <!-- /.card-body -->
      </div>
    </div>

    <div class="row">
      <div class="card" style="width: 100%;">
        <div class="card-header">
          <h3 class="card-title">Payments</h3>

          <div class="card-tools">
            <ul class="pagination pagination-sm float-right">
              <li class="page-item">
                <a class="create-payments page-link" href="#">
                  <i class="fa fa-plus"></i> New
                </a>
              </li>
            </ul>
          </div>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
          <div class="dataTables_wrapper dt-bootstrap4">
            <table id="payments-table" class="table table-bordered table-hover">
              <thead>
              <tr>
                <th class="text-center" scope="col">#</th>
                <th class="text-center" scope="col">Invoice ID</th>
                <th class="text-center" scope="col">Date</th>
                <th class="text-center" scope="col">Type</th>
                <th class="text-center" scope="col">Amounts</th>
                <th class="text-center" scope="col">Status</th>
                <th class="text-center" scope="col">Action</th>
              </tr>
              </thead>
              <tbody>
              {% for payment in payments %}
                <tr>
                  <td class="text-center" scope="row">{{ forloop.counter }}</td>
                  <td class="text-center">{{ payment.invoice_id }}</td>
                  <td class="text-center">{{ payment.payment_date }}</td>
                  <td class="text-center">{{ payment.type }}</td>
                  <td class="text-center">$ {{ payment.amount }}</td>
                  <td class="text-center">
                    <span class="badge {% if payment.status == 'paid' %}badge-info{% else %}badge-danger{% endif %}">{{ payment.status }}</span>
                  </td>
                  <td class="text-center">
                    <button type="button" class="update-payments btn btn-sm btn-primary" data-id="{% url 'dashboard:update-payment' payment.pk customer.pk %}">
                      <span class="fa fa-pen"></span>
                    </button>
                    <button type="button" class="delete-payments btn btn-sm btn-danger" data-id="{% url 'dashboard:delete-payment' payment.pk customer.pk %}">
                      <span class="fa fa-trash"></span>
                    </button>
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
        <!-- /.card-body -->
      </div>
    </div>
  {% endif %}
{% endblock content %}

{% block sub_extra_script %}
  <script src="{% static 'plugins/datatables/jquery.dataTables.js' %}"></script>
  <script src="{% static 'plugins/datatables-bs4/js/dataTables.bootstrap4.js' %}"></script>
  <script src="{% static 'plugins/toastr/toastr.min.js' %}"></script>
  <script src="{% static 'plugins/jquery.bootstrap.modal.forms.min.js' %}"></script>
  <script>
    $(function () {
      $('#earnings-table').DataTable({
        "paging": true,
        "lengthChange": false,
        "searching": false,
        "ordering": true,
        "info": true,
        "autoWidth": false,
      });
      $('#payments-table').DataTable({
        "paging": true,
        "lengthChange": false,
        "searching": false,
        "ordering": true,
        "info": true,
        "autoWidth": false,
      });

      // Update balance buttons
      $(".update-balance").each(function () {
        $(this).modalForm({formURL: $(this).data('id')});
      });

      // Create earnings button
      $(".create-earnings").modalForm({formURL: "{% url 'dashboard:create-earning' slug=customer.pk %}"});
      // Update earnings buttons
      $(".update-earnings").each(function () {
        $(this).modalForm({formURL: $(this).data('id')});
      });
      // Delete earnings buttons
      $(".delete-earnings").each(function () {
        $(this).modalForm({formURL: $(this).data('id')});
      });

      // Create payments button
      $(".create-payments").modalForm({formURL: "{% url 'dashboard:create-payment' slug=customer.pk %}"});
      // Update payments buttons
      $(".update-payments").each(function () {
        $(this).modalForm({formURL: $(this).data('id')});
      });
      // Delete payments buttons
      $(".delete-payments").each(function () {
        $(this).modalForm({formURL: $(this).data('id')});
      });
    });
  </script>

  {% for message in messages %}
    {% if message.tags == "info" %}
        <script> toastr.info('{{message}}')</script>
    {% elif message.tags == "error" %}
        <script> toastr.error('{{message}}')</script>
    {% elif message.tags == "warning" %}
        <script> toastr.warning('{{message}}')</script>
    {% elif message.tags == "success" %}
        <script> toastr.success('{{message}}')</script>
    {% endif %}
  {% endfor %}
{% endblock %}